#!/usr/bin/env python3

import argparse
import traceback

import traceface

def main():
	parser = argparse.ArgumentParser()
	parser.add_argument('code', metavar='CODE', type=str)
	parser.add_argument('-i', dest='module', type=str)
	args = parser.parse_args()

	run_globals = None
	if args.module is not None:
		module = __import__(args.module)
		run_globals = {module.__name__: module}
	tracer = traceface.Tracer()
	try:
		tracer.run(args.code, run_globals)
	except:
		traceback.print_exc()

	tracer.write_output()

if __name__ == '__main__':
	main()
